-- AlterEnum
ALTER TYPE "ServiceCategory" ADD VALUE 'RENTAL_CLOTHING_MEN';
ALTER TYPE "ServiceCategory" ADD VALUE 'RENTAL_CLOTHING_WOMEN';
ALTER TYPE "ServiceCategory" ADD VALUE 'RENTAL_CLOTHING_CHILD';
ALTER TYPE "ServiceCategory" ADD VALUE 'RENTAL_CAR';
ALTER TYPE "ServiceCategory" ADD VALUE 'RENTAL_MOTO';
ALTER TYPE "ServiceCategory" ADD VALUE 'RENTAL_EQUIPMENT';
