type TemplateElement = Record<string, unknown>;

export const GLOBAL_CATALOG_TEMPLATES: Array<{
  name: string;
  showOnLanding: boolean;
  global: Record<string, unknown>;
  elements: TemplateElement[];
}> = [
  {
    name: 'Pinterest Boho Chic — Mariage Eucalyptus & Or',
    showOnLanding: true,
    global: {
      bgType: 'pattern',
      bgPattern: 'paper',
      bgColor: '#fdfbf7',
      frameType: 'arch',
      floralColor: '#7d8c5c',
      floralType: 'eucalyptus',
      floralDensity: 28,
      fontTheme: 'romantic',
      canvasSizePreset: 'standard',
      canvasWidth: 480,
      canvasHeight: 740,
      landingCategory: 'wedding',
      landingDescription: 'Inspiration Pinterest : Arche florale végétale, eucalyptus poudré, typographie manuscrite élégante et dorure subtile.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'p1_1', type: 'text', text: 'SAVE THE DATE', color: '#8a9a6e', fontSize: '11px', align: 'center', bold: true, letterSpacing: '0.28em' },
      { id: 'p1_2', type: 'text', text: '{{title}}', color: '#2d3a29', fontSize: '36px', align: 'center', fontFamily: 'Cormorant Garamond', italic: true },
      { id: 'p1_3', type: 'divider', dividerStyle: 'ornament-leaves', color: '#7d8c5c', align: 'center' },
      { id: 'p1_4', type: 'text', text: 'Cher(e) {{firstName}}, nous avons la joie de vous convier à notre célébration', color: '#5a6854', fontSize: '13px', align: 'center' },
      { id: 'p1_5', type: 'text', text: 'Le {{date}}\n{{location}}', color: '#2d3a29', fontSize: '14px', align: 'center', bold: true },
      { id: 'p1_6', type: 'divider', dividerStyle: 'solid', color: '#cbd5b9', align: 'center' },
      { id: 'p1_7', type: 'text', text: 'Cocktail champêtre, dîner sous les lampions & soirée festive', color: '#6a7864', fontSize: '12px', align: 'center', italic: true },
      { id: 'p1_8', type: 'rsvp-block', text: 'Confirmer votre présence', color: '#4e6347', fontSize: '15px', align: 'center', rsvpPlacement: 'outside' },
    ],
  },
  {
    name: 'Pinterest Minimaliste Vogue — Typographie Albâtre',
    showOnLanding: true,
    global: {
      bgType: 'color',
      bgColor: '#fcfaf6',
      frameType: 'double-border',
      fontTheme: 'minimal',
      canvasSizePreset: 'standard',
      canvasWidth: 480,
      canvasHeight: 720,
      landingCategory: 'private',
      landingDescription: 'Inspiration Pinterest : Style éditorial haute couture, typographie serif étirée, ivoire albâtre et élégance pure.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'p2_1', type: 'text', text: 'INVITATION OFFICIELLE', color: '#78716c', fontSize: '10px', align: 'center', letterSpacing: '0.35em' },
      { id: 'p2_2', type: 'text', text: '{{title}}', color: '#1c1917', fontSize: '24px', align: 'center', fontFamily: 'Cinzel', bold: true, letterSpacing: '0.18em' },
      { id: 'p2_3', type: 'divider', dividerStyle: 'ornament-diamond', color: '#a8a29e', align: 'center' },
      { id: 'p2_4', type: 'text', text: 'Cher(e) {{firstName}}, vous êtes chaleureusement convié(e) à célébrer ce moment d’exception', color: '#78716c', fontSize: '11px', align: 'center', letterSpacing: '0.22em' },
      { id: 'p2_5', type: 'text', text: 'Le {{date}}', color: '#1c1917', fontSize: '20px', align: 'center', bold: true, letterSpacing: '0.15em' },
      { id: 'p2_6', type: 'text', text: '{{location}}', color: '#57534e', fontSize: '12px', align: 'center', letterSpacing: '0.18em' },
      { id: 'p2_7', type: 'text', text: 'Cocktail · Dîner · Soirée festive · Dress Code Élégant', color: '#78716c', fontSize: '12px', align: 'center' },
      { id: 'p2_8', type: 'button', text: 'R . S . V . P', color: '#1c1917', fontSize: '12px', align: 'center', buttonStyle: 'outline', buttonLink: '#rsvp-section' },
      { id: 'p2_9', type: 'rsvp-block', text: 'Confirmer votre présence', color: '#1c1917', fontSize: '15px', align: 'center', rsvpPlacement: 'outside' },
    ],
  },
  {
    name: 'Pinterest Black Tie Luxe — Or Velours & Gala VIP',
    showOnLanding: true,
    global: {
      bgType: 'color',
      bgColor: '#0c0e12',
      frameType: 'gold-border',
      fontTheme: 'classic',
      floralColor: '#d4af37',
      canvasSizePreset: 'standard',
      canvasWidth: 480,
      canvasHeight: 740,
      landingCategory: 'gala',
      landingDescription: 'Inspiration Pinterest : Ambiance nocturne prestige, cadre or étincelant, noir velours profond et dress code Black Tie.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'p3_1', type: 'text', text: '★   PASS PRIVILÈGE VIP   ★', color: '#eab308', fontSize: '10px', align: 'center', bold: true, letterSpacing: '0.3em' },
      { id: 'p3_2', type: 'text', text: '{{title}}', color: '#fef08a', fontSize: '28px', align: 'center', fontFamily: 'Cinzel', bold: true, letterSpacing: '0.12em' },
      { id: 'p3_3', type: 'divider', dividerStyle: 'ornament-star', color: '#ca8a04', align: 'center' },
      { id: 'p3_4', type: 'text', text: 'Cher(e) {{firstName}}, rejoignez-nous pour une nuit d\'exception et de prestige', color: '#fef9c3', fontSize: '14px', align: 'center', fontFamily: 'Cormorant Garamond', italic: true },
      { id: 'p3_5', type: 'text', text: 'Le {{date}}\n{{location}}', color: '#fde047', fontSize: '14px', align: 'center', bold: true },
      { id: 'p3_6', type: 'text', text: 'Coupe de champagne · Dîner gastronomique · Set DJ privé', color: '#cbd5e1', fontSize: '12px', align: 'center' },
      { id: 'p3_7', type: 'text', text: 'Tenue de soirée exigée (Smoking & Robe longue)', color: '#94a3b8', fontSize: '11px', align: 'center', bold: true, letterSpacing: '0.15em' },
      { id: 'p3_8', type: 'rsvp-block', text: 'Confirmer ma présence au Gala', color: '#eab308', fontSize: '15px', align: 'center', rsvpPlacement: 'outside' },
    ],
  },
  {
    name: 'Pinterest Terracotta & Pampas — Célébration Solaire',
    showOnLanding: true,
    global: {
      bgType: 'pattern',
      bgPattern: 'boho',
      bgColor: '#fbf4ee',
      frameType: 'arch',
      floralColor: '#c25e40',
      fontTheme: 'romantic',
      canvasSizePreset: 'standard',
      canvasWidth: 480,
      canvasHeight: 740,
      landingCategory: 'birthday',
      landingDescription: 'Inspiration Pinterest : Teintes chaudes terracotta, argile et beige lin, arche contemporaine et esprit bohème estival.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'p4_1', type: 'text', text: 'C É L É B R A T I O N', color: '#b45309', fontSize: '11px', align: 'center', bold: true, letterSpacing: '0.3em' },
      { id: 'p4_2', type: 'text', text: '{{title}}', color: '#9a3412', fontSize: '32px', align: 'center', fontFamily: 'Great Vibes' },
      { id: 'p4_3', type: 'divider', dividerStyle: 'ornament-flower', color: '#c25e40', align: 'center' },
      { id: 'p4_4', type: 'text', text: 'Cher(e) {{firstName}}, venez trinquer et fêter avec nous cette journée si particulière', color: '#7c2d12', fontSize: '13px', align: 'center' },
      { id: 'p4_5', type: 'text', text: 'Le {{date}}\n{{location}}', color: '#431407', fontSize: '14px', align: 'center', bold: true },
      { id: 'p4_6', type: 'text', text: 'Barbecue gourmet, musique acoustique & bar à cocktails', color: '#9a3412', fontSize: '12px', align: 'center', italic: true },
      { id: 'p4_7', type: 'rsvp-block', text: 'Je confirme ma présence', color: '#c25e40', fontSize: '15px', align: 'center', rsvpPlacement: 'outside' },
    ],
  },
  {
    name: 'Pinterest Douceur Pastel — Baby Shower & Petit Ange',
    showOnLanding: true,
    global: {
      bgType: 'pattern',
      bgPattern: 'watercolor',
      bgColor: '#fdf7f9',
      frameType: 'floral-wreath',
      floralColor: '#f472b6',
      fontTheme: 'romantic',
      canvasSizePreset: 'standard',
      canvasWidth: 480,
      canvasHeight: 720,
      landingCategory: 'baptism',
      landingDescription: 'Inspiration Pinterest : Tons poudrés rose blush et blanc nuage, couronne douce, esprit layette chic et papillons.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'p5_1', type: 'text', text: 'UN PETIT MIRACLE ARRIVE', color: '#db2777', fontSize: '11px', align: 'center', bold: true, letterSpacing: '0.25em' },
      { id: 'p5_2', type: 'text', text: '{{title}}', color: '#831843', fontSize: '30px', align: 'center', fontFamily: 'Cormorant Garamond', italic: true },
      { id: 'p5_3', type: 'divider', dividerStyle: 'ornament-star', color: '#f472b6', align: 'center' },
      { id: 'p5_4', type: 'text', text: 'Cher(e) {{firstName}}, rejoignez-nous pour célébrer cet heureux événement', color: '#9d174d', fontSize: '13px', align: 'center' },
      { id: 'p5_5', type: 'text', text: 'Le {{date}}\n{{location}}', color: '#500724', fontSize: '14px', align: 'center', bold: true },
      { id: 'p5_6', type: 'text', text: 'Goûter gourmand, jeux souvenirs & bar à friandises', color: '#be185d', fontSize: '12px', align: 'center' },
      { id: 'p5_7', type: 'rsvp-block', text: 'Confirmer ma venue', color: '#db2777', fontSize: '15px', align: 'center', rsvpPlacement: 'outside' },
    ],
  },
  {
    name: 'Pinterest Garden Party — Sauge & Tonnelle Chic',
    showOnLanding: true,
    global: {
      bgType: 'color',
      bgColor: '#f3f7f4',
      frameType: 'double-border',
      floralColor: '#15803d',
      fontTheme: 'modern',
      canvasSizePreset: 'standard',
      canvasWidth: 480,
      canvasHeight: 720,
      landingCategory: 'casual',
      landingDescription: 'Inspiration Pinterest : Vert sauge lumineux, tonnelle fleurie, cocktails rafraîchissants et ambiance fête champêtre.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'p6_1', type: 'text', text: 'A F T E R W O R K   &   C O C K T A I L', color: '#166534', fontSize: '10px', align: 'center', bold: true, letterSpacing: '0.26em' },
      { id: 'p6_2', type: 'text', text: '{{title}}', color: '#14532d', fontSize: '28px', align: 'center', fontFamily: 'Playfair Display' },
      { id: 'p6_3', type: 'divider', dividerStyle: 'ornament-leaves', color: '#22c55e', align: 'center' },
      { id: 'p6_4', type: 'text', text: 'Cher(e) {{firstName}}, cocktails signatures, musique live & buffet gourmand', color: '#166534', fontSize: '13px', align: 'center' },
      { id: 'p6_5', type: 'text', text: 'Le {{date}}\n{{location}}', color: '#052e16', fontSize: '14px', align: 'center', bold: true },
      { id: 'p6_6', type: 'text', text: 'Ambiance chill & festive · Tenue Garden Casual', color: '#15803d', fontSize: '12px', align: 'center', italic: true },
      { id: 'p6_7', type: 'rsvp-block', text: 'Réserver ma place au cocktail', color: '#15803d', fontSize: '15px', align: 'center', rsvpPlacement: 'outside' },
    ],
  },
  {
    name: 'Mariage Élégant — Or & Ivoire',
    showOnLanding: true,
    global: {
      bgColor: '#fdf8f3',
      floralColor: '#c5a059',
      landingCategory: 'wedding',
      landingDescription: 'Cérémonie et réception, ton or et ivoire.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'NOUS VOUS INVITONS', color: '#c5a059', fontSize: '11px', align: 'center', letterSpacing: '0.2em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#78350f', fontSize: '30px', align: 'center', fontFamily: 'Cormorant Garamond' },
      { id: 'g3', type: 'divider', dividerStyle: 'ornament-flower', color: '#c5a059', align: 'center' },
      { id: 'g4', type: 'text', text: 'Cher(e) {{firstName}}, rejoignez-nous le {{date}} à {{location}} pour une célébration inoubliable.', color: '#57534e', fontSize: '14px', align: 'center' },
      { id: 'g5', type: 'rsvp-block', text: 'Confirmer ma présence', color: '#c5a059', fontSize: '15px', align: 'center', rsvpPlacement: 'outside' },
    ],
  },
  {
    name: 'Mariage Kuba — Rouge & Or',
    showOnLanding: true,
    global: {
      bgColor: '#1c0a0a',
      bgType: 'image',
      bgImageUrl: 'https://images.unsplash.com/photo-1648328414427-fc902f51808c?auto=format&fit=crop&w=900&q=80',
      floralColor: '#d4a017',
      landingCategory: 'wedding',
      landingDescription: 'Inspiration textile kuba, rouge profond & or avec couple traditionnel royal.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'LOANGO YA LIBALA', color: '#d4a017', fontSize: '11px', align: 'center', letterSpacing: '0.18em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#fef3c7', fontSize: '32px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, célébration le {{date}} à {{location}} · Tenue traditionnelle souhaitée', color: '#fca5a5', fontSize: '13px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Confirmer ma présence', color: '#d4a017', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Mariage Jardin — Vert Nil',
    showOnLanding: true,
    global: {
      bgColor: '#f0fdf4',
      floralColor: '#15803d',
      landingCategory: 'wedding',
      landingDescription: 'Cérémonie en extérieur, tons botaniques.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'SAVE THE DATE', color: '#15803d', fontSize: '11px', align: 'center', letterSpacing: '0.2em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#14532d', fontSize: '28px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, cérémonie civile le {{date}} puis cocktail à {{location}}.', color: '#3f6212', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Répondre', color: '#15803d', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Baptême Famille — Ciel',
    showOnLanding: true,
    global: {
      bgColor: '#f0f9ff',
      floralColor: '#0284c7',
      landingCategory: 'baptism',
      landingDescription: 'Baptême et bénédiction, pastel.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'BAPTÊME', color: '#0284c7', fontSize: '12px', align: 'center', letterSpacing: '0.22em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#0c4a6e', fontSize: '28px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, messe le {{date}} suivie d’un goûter en famille à {{location}}.', color: '#075985', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Confirmer', color: '#0284c7', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Anniversaire Festif — Pop',
    showOnLanding: true,
    global: {
      bgColor: '#fff7ed',
      bgPattern: 'watercolor',
      floralColor: '#ea580c',
      landingCategory: 'birthday',
      landingDescription: 'Anniversaire coloré, buffet et musique.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: "C'EST LA FÊTE !", color: '#ea580c', fontSize: '12px', align: 'center', bold: true },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#9a3412', fontSize: '28px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, venez célébrer avec nous le {{date}} à {{location}} !', color: '#7c2d12', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'button', text: 'Je serai là !', color: '#ea580c', fontSize: '14px', align: 'center', buttonStyle: 'pill', buttonLink: '#rsvp-section' },
      { id: 'g5', type: 'rsvp-block', text: 'Confirmer', color: '#ea580c', fontSize: '15px', align: 'center', rsvpPlacement: 'outside' },
    ],
  },
  {
    name: 'Anniversaire 50 ans — Bordeaux',
    showOnLanding: true,
    global: {
      bgColor: '#3b0d16',
      bgType: 'color',
      floralColor: '#f43f5e',
      landingCategory: 'birthday',
      landingDescription: 'Cinquantenaire, dîner assis.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'ANNIVERSAIRE', color: '#fda4af', fontSize: '12px', align: 'center', letterSpacing: '0.3em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#fff1f2', fontSize: '30px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, dîner, toasts et piste de danse le {{date}} à {{location}}.', color: '#fecdd3', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Répondre à l’invitation', color: '#e11d48', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Cérémonie religieuse — Ivoire',
    showOnLanding: true,
    global: {
      bgColor: '#fffbeb',
      floralColor: '#b45309',
      landingCategory: 'religious',
      landingDescription: 'Messe, consécration ou action de grâce.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'INVITATION', color: '#b45309', fontSize: '11px', align: 'center', letterSpacing: '0.2em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#78350f', fontSize: '26px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, vous êtes les bienvenus à l’église le {{date}} à {{location}} puis au repas.', color: '#92400e', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Confirmer ma présence', color: '#b45309', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Dot & fiançailles — Ocre',
    showOnLanding: true,
    global: {
      bgColor: '#fff7ed',
      bgType: 'image',
      bgImageUrl: 'https://images.unsplash.com/photo-1664645534653-b4b8b6473cb2?auto=format&fit=crop&w=900&q=80',
      floralColor: '#c2410c',
      landingCategory: 'wedding',
      landingDescription: 'Cérémonie de dot et fiançailles deux familles avec couple élégant.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'CÉRÉMONIE DE DOT', color: '#c2410c', fontSize: '11px', align: 'center', letterSpacing: '0.16em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#7c2d12', fontSize: '28px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, deux familles unies le {{date}} à {{location}} · Tenue traditionnelle', color: '#9a3412', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Confirmer', color: '#c2410c', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Gala Corporate — Bleu Nuit',
    showOnLanding: true,
    global: {
      bgColor: '#0f172a',
      bgType: 'color',
      frameType: 'none',
      landingCategory: 'gala',
      landingDescription: 'Gala d’entreprise, tenue de soirée.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: "SOIRÉE D'ENTREPRISE", color: '#93c5fd', fontSize: '11px', align: 'center', letterSpacing: '0.15em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#f8fafc', fontSize: '32px', align: 'center', bold: true },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, tenue de soirée le {{date}} à {{location}} · Cocktail & dîner assis', color: '#94a3b8', fontSize: '13px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: "Répondre à l'invitation", color: '#3b82f6', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Gala Prestige — Champagne',
    showOnLanding: true,
    global: {
      bgColor: '#1a1208',
      bgType: 'image',
      bgImageUrl: 'https://images.unsplash.com/photo-1768508951126-f90917cc510e?auto=format&fit=crop&w=900&q=80',
      floralColor: '#eab308',
      landingCategory: 'gala',
      landingDescription: 'Black tie, dîner d’exception et smoking.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'BLACK TIE', color: '#eab308', fontSize: '11px', align: 'center', letterSpacing: '0.28em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#fefce8', fontSize: '30px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, gala d’exception le {{date}} à {{location}}', color: '#fde68a', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Réserver ma place', color: '#ca8a04', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Conférence Pro — Minimal',
    showOnLanding: true,
    global: {
      bgColor: '#ffffff',
      frameType: 'double-border',
      landingCategory: 'conference',
      landingDescription: 'Conférence et networking.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'CONFÉRENCE & NETWORKING', color: '#4f46e5', fontSize: '11px', align: 'center' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#1e293b', fontSize: '26px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, rencontre professionnelle le {{date}} à {{location}} · Inscription obligatoire', color: '#475569', fontSize: '13px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Inscription', color: '#4f46e5', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Séminaire Leadership — Ardoise',
    showOnLanding: true,
    global: {
      bgColor: '#f8fafc',
      floralColor: '#334155',
      landingCategory: 'seminar',
      landingDescription: 'Journée séminaire et ateliers.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'SÉMINAIRE', color: '#334155', fontSize: '11px', align: 'center', letterSpacing: '0.2em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#0f172a', fontSize: '28px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, ateliers et plénière le {{date}} à {{location}}.', color: '#475569', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'S’inscrire', color: '#1e293b', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Lancement produit — Néon',
    showOnLanding: true,
    global: {
      bgColor: '#0b1020',
      bgType: 'color',
      floralColor: '#22d3ee',
      landingCategory: 'launch',
      landingDescription: 'Soirée de lancement de marque.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'LAUNCH NIGHT', color: '#22d3ee', fontSize: '11px', align: 'center', letterSpacing: '0.22em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#f8fafc', fontSize: '30px', align: 'center', bold: true },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, démo, cocktail et avant-première le {{date}} à {{location}}.', color: '#67e8f9', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Je participe', color: '#06b6d4', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Forum emploi — Vert',
    showOnLanding: true,
    global: {
      bgColor: '#ecfdf5',
      floralColor: '#047857',
      landingCategory: 'corporate',
      landingDescription: 'Forum et stands recruteurs.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'FORUM DE L’EMPLOI', color: '#047857', fontSize: '11px', align: 'center', letterSpacing: '0.14em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#064e3b', fontSize: '26px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, rencontrez les recruteurs le {{date}} à {{location}}.', color: '#065f46', fontSize: '13px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'S’inscrire', color: '#047857', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Cocktail networking — Ambre',
    showOnLanding: true,
    global: {
      bgColor: '#fffbeb',
      floralColor: '#d97706',
      landingCategory: 'cocktail',
      landingDescription: 'Afterwork et échanges informels.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'AFTERWORK', color: '#d97706', fontSize: '12px', align: 'center', letterSpacing: '0.24em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#78350f', fontSize: '28px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, cocktail & rencontres le {{date}} à {{location}}.', color: '#92400e', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Je viens', color: '#d97706', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Garden party — Menthe',
    showOnLanding: true,
    global: {
      bgColor: '#f7fee7',
      floralColor: '#65a30d',
      landingCategory: 'party',
      landingDescription: 'Réception en jardin, buffet.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'GARDEN PARTY', color: '#65a30d', fontSize: '11px', align: 'center', letterSpacing: '0.2em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#365314', fontSize: '28px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, après-midi au jardin le {{date}} à {{location}} · Buffet & musique live', color: '#4d7c0f', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Confirmer', color: '#65a30d', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Soirée DJ — Magenta',
    showOnLanding: true,
    global: {
      bgColor: '#2e0614',
      bgType: 'color',
      floralColor: '#e879f9',
      landingCategory: 'club',
      landingDescription: 'Club night, set DJ.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'CLUB NIGHT', color: '#e879f9', fontSize: '12px', align: 'center', letterSpacing: '0.28em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#fdf4ff', fontSize: '28px', align: 'center', bold: true },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, set live et ambiance club le {{date}} à {{location}}.', color: '#f0abfc', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Sur la liste', color: '#c026d3', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Concert live — Indigo',
    showOnLanding: true,
    global: {
      bgColor: '#1e1b4b',
      bgType: 'color',
      floralColor: '#818cf8',
      landingCategory: 'concert',
      landingDescription: 'Concert et showcase.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'LIVE ON STAGE', color: '#a5b4fc', fontSize: '11px', align: 'center', letterSpacing: '0.22em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#eef2ff', fontSize: '30px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, concert d’exception le {{date}} à {{location}} · Badge QR requis', color: '#c7d2fe', fontSize: '13px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Réserver', color: '#6366f1', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Open mic — Cuivre',
    showOnLanding: true,
    global: {
      bgColor: '#1c1917',
      bgType: 'color',
      floralColor: '#f97316',
      landingCategory: 'concert',
      landingDescription: 'Scène ouverte et spoken word.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'OPEN MIC', color: '#fb923c', fontSize: '12px', align: 'center', letterSpacing: '0.24em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#fff7ed', fontSize: '28px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, poésie, rap et acoustique le {{date}} à {{location}}', color: '#fdba74', fontSize: '13px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Je viens', color: '#ea580c', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Brunch networking — Crème',
    showOnLanding: true,
    global: {
      bgColor: '#fff1f2',
      floralColor: '#be123c',
      landingCategory: 'cocktail',
      landingDescription: 'Brunch d’affaires le dimanche.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'SUNDAY BRUNCH', color: '#be123c', fontSize: '11px', align: 'center', letterSpacing: '0.18em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#881337', fontSize: '28px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, brunch d’affaires le {{date}} à {{location}} · Places limitées', color: '#9f1239', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Réserver', color: '#e11d48', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Défilé de mode — Noir',
    showOnLanding: false,
    global: {
      bgColor: '#0a0a0a',
      bgType: 'color',
      floralColor: '#f5f5f4',
      landingCategory: 'party',
      landingDescription: 'Fashion show et sape.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'FASHION SHOW', color: '#a8a29e', fontSize: '11px', align: 'center', letterSpacing: '0.3em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#fafaf9', fontSize: '30px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, la Haute Couture à l’honneur le {{date}} à {{location}}', color: '#d6d3d1', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Confirmer', color: '#e7e5e4', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Salon du mariage — Rose',
    showOnLanding: false,
    global: {
      bgColor: '#fff1f2',
      floralColor: '#db2777',
      landingCategory: 'wedding',
      landingDescription: 'Salon exposants mariage.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'SALON DU MARIAGE', color: '#db2777', fontSize: '11px', align: 'center', letterSpacing: '0.16em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#9d174d', fontSize: '26px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, trouvez vos prestataires le {{date}} à {{location}}', color: '#be185d', fontSize: '13px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'S’inscrire', color: '#db2777', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Masterclass — Cobalt',
    showOnLanding: false,
    global: {
      bgColor: '#eff6ff',
      floralColor: '#1d4ed8',
      landingCategory: 'seminar',
      landingDescription: 'Atelier expert, places limitées.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'MASTERCLASS', color: '#1d4ed8', fontSize: '11px', align: 'center', letterSpacing: '0.2em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#1e3a8a', fontSize: '28px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, atelier d’experts le {{date}} à {{location}}', color: '#1e40af', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Réserver ma place', color: '#2563eb', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Soirée dansante — Tropique',
    showOnLanding: false,
    global: {
      bgColor: '#042f2e',
      bgType: 'color',
      floralColor: '#2dd4bf',
      landingCategory: 'party',
      landingDescription: 'Bal et rumba congolaise.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'g1', type: 'text', text: 'RUMBA NIGHT', color: '#5eead4', fontSize: '11px', align: 'center', letterSpacing: '0.22em' },
      { id: 'g2', type: 'text', text: '{{title}}', color: '#ccfbf1', fontSize: '30px', align: 'center' },
      { id: 'g3', type: 'text', text: 'Cher(e) {{firstName}}, orchestre live et danse le {{date}} à {{location}}', color: '#99f6e4', fontSize: '14px', align: 'center' },
      { id: 'g4', type: 'rsvp-block', text: 'Je danse', color: '#14b8a6', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Art Déco Gatsby — Or & Noir Ébène',
    showOnLanding: true,
    global: {
      bgColor: '#0f0f11',
      bgType: 'pattern',
      bgPattern: 'art-deco-geom',
      frameType: 'art-deco',
      fontTheme: 'art-deco',
      landingCategory: 'gala',
      landingDescription: 'Grand gala des années folles, dorures métalliques et symétrie Gatsby.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'ad1', type: 'text', text: 'THE GREAT GALA', color: '#d4af37', fontSize: '11px', align: 'center', letterSpacing: '0.3em' },
      { id: 'ad2', type: 'text', text: '{{title}}', color: '#fef3c7', fontSize: '30px', align: 'center', fontFamily: 'Cinzel' },
      { id: 'ad3', type: 'divider', dividerStyle: 'ornament-flower', color: '#d4af37', align: 'center' },
      { id: 'ad4', type: 'text', text: 'Cher(e) {{firstName}}, smoking & robe de soirée le {{date}} à {{location}} · Champagne & Jazz', color: '#d1d5db', fontSize: '13px', align: 'center' },
      { id: 'ad5', type: 'rsvp-block', text: 'Réserver ma table VIP', color: '#d4af37', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Afro-Luxe Royal — Velours du Kasaï',
    showOnLanding: true,
    global: {
      bgColor: '#24140e',
      bgType: 'pattern',
      bgPattern: 'kuba-weave',
      frameType: 'gold-border',
      fontTheme: 'afro-royal',
      landingCategory: 'wedding',
      landingDescription: 'Célébration traditionnelle royale, motifs Kuba et broderies d’or.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'al1', type: 'text', text: 'CÉLÉBRATION ROYALE', color: '#f59e0b', fontSize: '11px', align: 'center', letterSpacing: '0.24em' },
      { id: 'al2', type: 'text', text: '{{title}}', color: '#fef3c7', fontSize: '30px', align: 'center', fontFamily: 'Playfair Display' },
      { id: 'al3', type: 'text', text: 'Cher(e) {{firstName}}, grandeur, honneur et tradition le {{date}} à {{location}}', color: '#fed7aa', fontSize: '13px', align: 'center' },
      { id: 'al4', type: 'rsvp-block', text: 'Confirmer votre présence', color: '#ea580c', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Quiet Luxury — Lin & Gaufrage Blanc',
    showOnLanding: true,
    global: {
      bgColor: '#fcfbf9',
      bgType: 'pattern',
      bgPattern: 'deckled-cotton',
      frameType: 'embossed-arch',
      fontTheme: 'quiet-luxury',
      landingCategory: 'wedding',
      landingDescription: 'Mariage haute couture, gaufrage à sec sculptural et élégance discrète.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'ql1', type: 'text', text: 'ENSEMBLE', color: '#78716c', fontSize: '10px', align: 'center', letterSpacing: '0.35em' },
      { id: 'ql2', type: 'text', text: '{{title}}', color: '#1c1917', fontSize: '32px', align: 'center', fontFamily: 'Prata' },
      { id: 'ql3', type: 'text', text: 'Cher(e) {{firstName}}, vous êtes chaleureusement convié(e) à célébrer notre union le {{date}} à {{location}}', color: '#57534e', fontSize: '13px', align: 'center', fontFamily: 'Montserrat' },
      { id: 'ql4', type: 'rsvp-block', text: 'Confirmer ma venue', color: '#44403c', fontSize: '14px', align: 'center' },
    ],
  },
  {
    name: 'Passeport VIP Gala — Noir & Or Sécurisé',
    showOnLanding: true,
    global: {
      bgColor: '#16181f',
      bgType: 'pattern',
      bgPattern: 'gold-dust',
      frameType: 'passport-vip',
      fontTheme: 'editorial',
      landingCategory: 'gala',
      landingDescription: 'Invitation format passeport diplomatique pour donateurs et invités VIP.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'pv1', type: 'text', text: 'RÉPUBLIQUE DE L’ÉVÉNEMENT · BILLET D’HONNEUR', color: '#d4af37', fontSize: '10px', align: 'center', letterSpacing: '0.2em' },
      { id: 'pv2', type: 'text', text: '{{title}}', color: '#f8fafc', fontSize: '28px', align: 'center', fontFamily: 'Cinzel' },
      { id: 'pv3', type: 'text', text: 'Cher(e) {{firstName}}, accès prioritaire au salon VIP le {{date}} à {{location}}', color: '#94a3b8', fontSize: '12px', align: 'center' },
      { id: 'pv4', type: 'rsvp-block', text: 'Activer mon badge VIP', color: '#ca8a04', fontSize: '15px', align: 'center' },
    ],
  },
  {
    name: 'Cyber Keynote — Verre Dépoli & Néon Cyan',
    showOnLanding: true,
    global: {
      bgColor: '#0b0f19',
      bgType: 'pattern',
      bgPattern: 'vellum',
      frameType: 'frosted-glass',
      fontTheme: 'modern',
      landingCategory: 'launch',
      landingDescription: 'Lancement de produit high-tech, design modulaire et verre dépoli.',
      isPublicTemplate: true,
      hasCustomizableVariables: true,
    },
    elements: [
      { id: 'ck1', type: 'text', text: 'NEXT-GEN REVEAL', color: '#06b6d4', fontSize: '11px', align: 'center', letterSpacing: '0.25em' },
      { id: 'ck2', type: 'text', text: '{{title}}', color: '#f8fafc', fontSize: '30px', align: 'center', bold: true },
      { id: 'ck3', type: 'text', text: 'Cher(e) {{firstName}}, keynote et immersion technologique le {{date}} à {{location}}', color: '#94a3b8', fontSize: '13px', align: 'center' },
      { id: 'ck4', type: 'rsvp-block', text: 'Réserver mon pass', color: '#0891b2', fontSize: '15px', align: 'center' },
    ],
  },
];
