-- AlterEnum
ALTER TYPE "PlanType" ADD VALUE 'PERSONAL_50';
ALTER TYPE "PlanType" ADD VALUE 'PERSONAL_100';
ALTER TYPE "PlanType" ADD VALUE 'PERSONAL_200';
ALTER TYPE "PlanType" ADD VALUE 'PERSONAL_PLUS';
