export const PLATFORM_NOTIFICATION_TYPE = {
  SUBSCRIPTION_APPROVAL: 'SUBSCRIPTION_APPROVAL',
  ADMIN_ACTIVATION: 'ADMIN_ACTIVATION',
  ADMIN_RENEWAL: 'ADMIN_RENEWAL',
  ADMIN_PLAN_CHANGE: 'ADMIN_PLAN_CHANGE',
  LICENSE_RENEWAL: 'LICENSE_RENEWAL',
  MONTHLY_COMMISSION_DUE: 'MONTHLY_COMMISSION_DUE',
  MONTHLY_COMMISSION_PAID: 'MONTHLY_COMMISSION_PAID',
  SUBSCRIPTION_REQUEST_PENDING: 'SUBSCRIPTION_REQUEST_PENDING',
  LICENSE_EXPIRING: 'LICENSE_EXPIRING',
  INVOICE_ISSUED: 'INVOICE_ISSUED',
  MARKETPLACE_INQUIRY: 'MARKETPLACE_INQUIRY',
  MARKETPLACE_BOOKING: 'MARKETPLACE_BOOKING',
  MARKETPLACE_BOOKING_STATUS: 'MARKETPLACE_BOOKING_STATUS',
  EVENT_TASK_ASSIGNED: 'EVENT_TASK_ASSIGNED',
  EVENT_TASK_DUE: 'EVENT_TASK_DUE',
  EVENT_TASK_COMPLETED: 'EVENT_TASK_COMPLETED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  TICKET_SALE: 'TICKET_SALE',
  TICKET_PAYMENT_FAILED: 'TICKET_PAYMENT_FAILED',
  EVENT_RSVP: 'EVENT_RSVP',
  DISCOUNT_REQUEST_PENDING: 'DISCOUNT_REQUEST_PENDING',
  DISCOUNT_QUOTE_READY: 'DISCOUNT_QUOTE_READY',
} as const;

export type NotificationFamily = 'events' | 'billing' | 'commissions' | 'catalog' | 'tasks' | 'all';
export type NotificationPrefFamily = Exclude<NotificationFamily, 'all'>;

export const NOTIFICATION_PREF_FAMILIES: NotificationPrefFamily[] = [
  'events',
  'billing',
  'commissions',
  'catalog',
  'tasks',
];

export const NOTIFICATION_FAMILY_LABELS: Record<NotificationPrefFamily, string> = {
  events: 'Événements',
  billing: 'Facturation',
  commissions: 'Commissions',
  catalog: 'Catalogue',
  tasks: 'Tâches',
};

export const NOTIFICATION_FAMILY_DESCRIPTIONS: Record<NotificationPrefFamily, string> = {
  events: 'Réponses RSVP, billets vendus et paiements de places qui n’aboutissent pas.',
  billing: 'Factures, abonnements, licences et demandes de rabais.',
  commissions: 'Commissions mensuelles à encaisser ou déjà payées.',
  catalog: 'Demandes et réservations marketplace (salles, services).',
  tasks: 'Tâches d’événement assignées, à échéance ou terminées.',
};

const EVENT_TYPES = new Set([
  PLATFORM_NOTIFICATION_TYPE.EVENT_RSVP,
  PLATFORM_NOTIFICATION_TYPE.TICKET_SALE,
  PLATFORM_NOTIFICATION_TYPE.TICKET_PAYMENT_FAILED,
]);

const BILLING_TYPES = new Set([
  PLATFORM_NOTIFICATION_TYPE.SUBSCRIPTION_APPROVAL,
  PLATFORM_NOTIFICATION_TYPE.ADMIN_ACTIVATION,
  PLATFORM_NOTIFICATION_TYPE.ADMIN_RENEWAL,
  PLATFORM_NOTIFICATION_TYPE.ADMIN_PLAN_CHANGE,
  PLATFORM_NOTIFICATION_TYPE.LICENSE_RENEWAL,
  PLATFORM_NOTIFICATION_TYPE.SUBSCRIPTION_REQUEST_PENDING,
  PLATFORM_NOTIFICATION_TYPE.LICENSE_EXPIRING,
  PLATFORM_NOTIFICATION_TYPE.INVOICE_ISSUED,
  PLATFORM_NOTIFICATION_TYPE.PAYMENT_RECEIVED,
  PLATFORM_NOTIFICATION_TYPE.DISCOUNT_REQUEST_PENDING,
  PLATFORM_NOTIFICATION_TYPE.DISCOUNT_QUOTE_READY,
]);

const COMMISSION_TYPES = new Set([
  PLATFORM_NOTIFICATION_TYPE.MONTHLY_COMMISSION_DUE,
  PLATFORM_NOTIFICATION_TYPE.MONTHLY_COMMISSION_PAID,
]);

const CATALOG_TYPES = new Set([
  PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_INQUIRY,
  PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_BOOKING,
  PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_BOOKING_STATUS,
]);

const TASK_TYPES = new Set([
  PLATFORM_NOTIFICATION_TYPE.EVENT_TASK_ASSIGNED,
  PLATFORM_NOTIFICATION_TYPE.EVENT_TASK_DUE,
  PLATFORM_NOTIFICATION_TYPE.EVENT_TASK_COMPLETED,
]);

export function notificationFamily(type: string): Exclude<NotificationFamily, 'all'> | 'account' {
  if (EVENT_TYPES.has(type as never)) return 'events';
  if (BILLING_TYPES.has(type as never)) return 'billing';
  if (COMMISSION_TYPES.has(type as never)) return 'commissions';
  if (CATALOG_TYPES.has(type as never)) return 'catalog';
  if (TASK_TYPES.has(type as never)) return 'tasks';
  return 'account';
}

export function notificationFamilyLabel(type: string): string {
  const family = notificationFamily(type);
  if (family === 'account') return 'Compte';
  return NOTIFICATION_FAMILY_LABELS[family];
}

const TYPE_LABELS: Record<string, string> = {
  [PLATFORM_NOTIFICATION_TYPE.TICKET_SALE]: 'Billet',
  [PLATFORM_NOTIFICATION_TYPE.TICKET_PAYMENT_FAILED]: 'Paiement billet',
  [PLATFORM_NOTIFICATION_TYPE.EVENT_RSVP]: 'RSVP',
  [PLATFORM_NOTIFICATION_TYPE.PAYMENT_RECEIVED]: 'Paiement',
  [PLATFORM_NOTIFICATION_TYPE.SUBSCRIPTION_REQUEST_PENDING]: 'Abonnement',
  [PLATFORM_NOTIFICATION_TYPE.DISCOUNT_REQUEST_PENDING]: 'Rabais',
  [PLATFORM_NOTIFICATION_TYPE.LICENSE_EXPIRING]: 'Licence',
  [PLATFORM_NOTIFICATION_TYPE.MONTHLY_COMMISSION_DUE]: 'Commission',
  [PLATFORM_NOTIFICATION_TYPE.MONTHLY_COMMISSION_PAID]: 'Commission',
  [PLATFORM_NOTIFICATION_TYPE.INVOICE_ISSUED]: 'Facture',
  [PLATFORM_NOTIFICATION_TYPE.DISCOUNT_QUOTE_READY]: 'Devis',
  [PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_INQUIRY]: 'Demande',
  [PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_BOOKING]: 'Réservation',
};

export function notificationTypeLabel(type: string): string {
  return TYPE_LABELS[type] || notificationFamilyLabel(type);
}
