export const PLATFORM_NOTIFICATION_TYPE = {
  SUBSCRIPTION_APPROVAL: 'SUBSCRIPTION_APPROVAL',
  ADMIN_ACTIVATION: 'ADMIN_ACTIVATION',
  ADMIN_RENEWAL: 'ADMIN_RENEWAL',
  ADMIN_PLAN_CHANGE: 'ADMIN_PLAN_CHANGE',
  LICENSE_RENEWAL: 'LICENSE_RENEWAL',
  MONTHLY_COMMISSION_DUE: 'MONTHLY_COMMISSION_DUE',
  MONTHLY_COMMISSION_PAID: 'MONTHLY_COMMISSION_PAID',
  SUBSCRIPTION_REQUEST_PENDING: 'SUBSCRIPTION_REQUEST_PENDING',
  LICENSE_EXPIRING: 'LICENSE_EXPIRING',
  INVOICE_ISSUED: 'INVOICE_ISSUED',
  MARKETPLACE_INQUIRY: 'MARKETPLACE_INQUIRY',
  MARKETPLACE_BOOKING: 'MARKETPLACE_BOOKING',
  MARKETPLACE_BOOKING_STATUS: 'MARKETPLACE_BOOKING_STATUS',
  EVENT_TASK_ASSIGNED: 'EVENT_TASK_ASSIGNED',
  EVENT_TASK_DUE: 'EVENT_TASK_DUE',
  EVENT_TASK_COMPLETED: 'EVENT_TASK_COMPLETED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
} as const;

export type PlatformNotificationType =
  (typeof PLATFORM_NOTIFICATION_TYPE)[keyof typeof PLATFORM_NOTIFICATION_TYPE];

export const NOTIFICATION_FAMILIES = {
  billing: [
    PLATFORM_NOTIFICATION_TYPE.SUBSCRIPTION_APPROVAL,
    PLATFORM_NOTIFICATION_TYPE.ADMIN_ACTIVATION,
    PLATFORM_NOTIFICATION_TYPE.ADMIN_RENEWAL,
    PLATFORM_NOTIFICATION_TYPE.ADMIN_PLAN_CHANGE,
    PLATFORM_NOTIFICATION_TYPE.LICENSE_RENEWAL,
    PLATFORM_NOTIFICATION_TYPE.SUBSCRIPTION_REQUEST_PENDING,
    PLATFORM_NOTIFICATION_TYPE.LICENSE_EXPIRING,
    PLATFORM_NOTIFICATION_TYPE.INVOICE_ISSUED,
    PLATFORM_NOTIFICATION_TYPE.PAYMENT_RECEIVED,
  ],
  commissions: [
    PLATFORM_NOTIFICATION_TYPE.MONTHLY_COMMISSION_DUE,
    PLATFORM_NOTIFICATION_TYPE.MONTHLY_COMMISSION_PAID,
  ],
  catalog: [
    PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_INQUIRY,
    PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_BOOKING,
    PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_BOOKING_STATUS,
  ],
  tasks: [
    PLATFORM_NOTIFICATION_TYPE.EVENT_TASK_ASSIGNED,
    PLATFORM_NOTIFICATION_TYPE.EVENT_TASK_DUE,
    PLATFORM_NOTIFICATION_TYPE.EVENT_TASK_COMPLETED,
  ],
} as const;

export type NotificationFamily = keyof typeof NOTIFICATION_FAMILIES;

export const NOTIFICATION_PREF_FAMILIES = ['billing', 'commissions', 'catalog', 'tasks'] as const;
export type NotificationPrefFamily = (typeof NOTIFICATION_PREF_FAMILIES)[number];

export type NotificationChannel = 'IN_APP' | 'EMAIL' | 'WHATSAPP' | 'PUSH';

export function typesForFamily(family?: string | null): string[] | undefined {
  if (!family) return undefined;
  const key = family as NotificationFamily;
  const types = NOTIFICATION_FAMILIES[key];
  return types ? [...types] : undefined;
}

export function familyForType(type: string): NotificationPrefFamily | 'account' {
  if ((NOTIFICATION_FAMILIES.billing as readonly string[]).includes(type)) return 'billing';
  if ((NOTIFICATION_FAMILIES.commissions as readonly string[]).includes(type)) return 'commissions';
  if ((NOTIFICATION_FAMILIES.catalog as readonly string[]).includes(type)) return 'catalog';
  if ((NOTIFICATION_FAMILIES.tasks as readonly string[]).includes(type)) return 'tasks';
  return 'account';
}

export function isNotificationPrefFamily(value: string): value is NotificationPrefFamily {
  return (NOTIFICATION_PREF_FAMILIES as readonly string[]).includes(value);
}
