export const PLATFORM_NOTIFICATION_TYPE = {
  SUBSCRIPTION_APPROVAL: 'SUBSCRIPTION_APPROVAL',
  ADMIN_ACTIVATION: 'ADMIN_ACTIVATION',
  ADMIN_RENEWAL: 'ADMIN_RENEWAL',
  ADMIN_PLAN_CHANGE: 'ADMIN_PLAN_CHANGE',
  LICENSE_RENEWAL: 'LICENSE_RENEWAL',
  MONTHLY_COMMISSION_DUE: 'MONTHLY_COMMISSION_DUE',
  MONTHLY_COMMISSION_PAID: 'MONTHLY_COMMISSION_PAID',
  SUBSCRIPTION_REQUEST_PENDING: 'SUBSCRIPTION_REQUEST_PENDING',
  LICENSE_EXPIRING: 'LICENSE_EXPIRING',
  INVOICE_ISSUED: 'INVOICE_ISSUED',
  MARKETPLACE_INQUIRY: 'MARKETPLACE_INQUIRY',
  MARKETPLACE_BOOKING: 'MARKETPLACE_BOOKING',
  MARKETPLACE_BOOKING_STATUS: 'MARKETPLACE_BOOKING_STATUS',
} as const;

export type PlatformNotificationType =
  (typeof PLATFORM_NOTIFICATION_TYPE)[keyof typeof PLATFORM_NOTIFICATION_TYPE];

export const NOTIFICATION_FAMILIES = {
  billing: [
    PLATFORM_NOTIFICATION_TYPE.SUBSCRIPTION_APPROVAL,
    PLATFORM_NOTIFICATION_TYPE.ADMIN_ACTIVATION,
    PLATFORM_NOTIFICATION_TYPE.ADMIN_RENEWAL,
    PLATFORM_NOTIFICATION_TYPE.ADMIN_PLAN_CHANGE,
    PLATFORM_NOTIFICATION_TYPE.LICENSE_RENEWAL,
    PLATFORM_NOTIFICATION_TYPE.SUBSCRIPTION_REQUEST_PENDING,
    PLATFORM_NOTIFICATION_TYPE.LICENSE_EXPIRING,
    PLATFORM_NOTIFICATION_TYPE.INVOICE_ISSUED,
  ],
  commissions: [
    PLATFORM_NOTIFICATION_TYPE.MONTHLY_COMMISSION_DUE,
    PLATFORM_NOTIFICATION_TYPE.MONTHLY_COMMISSION_PAID,
  ],
  catalog: [
    PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_INQUIRY,
    PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_BOOKING,
    PLATFORM_NOTIFICATION_TYPE.MARKETPLACE_BOOKING_STATUS,
  ],
} as const;

export type NotificationFamily = keyof typeof NOTIFICATION_FAMILIES;

export function typesForFamily(family?: string | null): string[] | undefined {
  if (!family) return undefined;
  const key = family as NotificationFamily;
  const types = NOTIFICATION_FAMILIES[key];
  return types ? [...types] : undefined;
}
